### ISSUE TITLE
Docs do not mention since which version modules can use modern routing

### ISSUE THREAD

**Issue by michaelKaefer** [PrestaShop/docs#492]
Docs do not mention since which PrestaShop version modules can use modern routing like this:

```
# modules/your-module/config/routes.yml
your_route_name:
    path: your-module/demo
    methods: [GET]
    defaults:
      _controller: 'MyModule\Controller\DemoController::demoAction'
```

The docs are here: https://devdocs.prestashop.com/1.7/modules/concepts/controllers/admin-controllers/#how-to-map-an-action-of-your-controller-to-a-uri
